# Generated by Django 5.2.17 on 2026-08-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('api_call_limit', models.PositiveIntegerField(help_text='Maximum number of API calls a tenant on this tier may make per day.')),
            ],
            options={
                'ordering': ['monthly_price'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_price__gte', 0)), name='subscriptiontier_monthly_price_gte_0'), models.CheckConstraint(condition=models.Q(('api_call_limit__gt', 0)), name='subscriptiontier_api_call_limit_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='TenantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('billing_email', models.EmailField(max_length=254)),
                ('current_api_usage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='subscriptions.subscriptiontier')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
